import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export async function POST(request: Request) {
  try {
    const body = await request.json().catch(() => ({}));
    const title: string = body.title ?? "새 프로젝트";

    // shareToken is auto-generated by Prisma via @default(cuid())
    const project = await prisma.project.create({
      data: { title },
      select: { id: true, shareToken: true, title: true },
    });

    return NextResponse.json(project, { status: 201 });
  } catch (error) {
    console.error("[POST /api/projects]", error);
    return NextResponse.json({ error: "프로젝트 생성에 실패했습니다." }, { status: 500 });
  }
}
